package com.eclectics.chamapayments.service.enums;

/**
 * @author Alex Maina
 * @created 09/12/2021
 */
public enum PaymentEnum {
    DEFAULTED,
    PAYMENT_FAILED,
    PAYMENT_PENDING,
    PAYMENT_SUCCESS,
    KIT_TRANSFER_SUCCESS,
    PAYMENT_WRITTEN_OFF,
    TRANSFER_SUCCESS,
    PAID,
    NOT_FULLY_PAID,
    FULLY_PAID,
    YET_TO_PAY,
    DISBURSED,
    SENT_TO_OUTSTANDING_CONTRIBUTION,
    WITHDRAWN_AND_DISBURSED,
    SHARE_OUT_PENDING_DISBURSEMENT,
    SHARE_OUT_DISBURSED_SUCCESSFULLY,
    SHARE_OUT_COMPLETED_SUCCESSFULLY
}
